### ISSUE TITLE
Reading ease displayed incorrectly

### ISSUE THREAD

**Issue by bentley** [standardebooks/george-macdonald_at-the-back-of-the-north-wind#1]
Currently this book’s webpage [says](https://standardebooks.org/ebooks/george-macdonald/at-the-back-of-the-north-wind):

> 90,847 words (5 hours 31 minutes) with a reading ease of 89.48 ()

The second pair of parentheses is empty.

**Comment by acabal** [comment]
Thanks, this should be fixed now!
